[package]
name = "lotus-bindgen-macros"
version = "0.1.1"
edition = "2021"
description = "Reserved for future use"
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }
