[package]
name = "lotussim-script"
version = "0.8.5"
description = "A library for creating LOTUS-Simulator scripts."
documentation = "https://docs.rs/lotussim-script"
edition.workspace = true
license.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
features = ["time"]
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "lotus_script"

[features]
time = ["lotus-shared/time"]
internal = ["lotus-shared/internal"]

[dependencies]
lotus-bindgen-macros = { workspace = true }
lotus-script-sys.workspace = true
lotus-shared = { workspace = true, features = ["ffi"] }
rmp-serde.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_repr.workspace = true
thiserror.workspace = true
